name: cookie_update_alarm

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 1,16 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
    - name: Use Node.js For Work
      run: npm ci && node updateCookie.js
