name: cookie_update_alarm

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 1,16 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
    - name: cookie update alarm
      env:
        JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: npm ci && node updateCookie.js "${PUSH_TOKEN}"
